### ISSUE TITLE
How do you treat application reboots without recreating projections?

### ISSUE THREAD

**Issue by ieugen** [Baeldung/spring-event-sourcing-and-cqrs#1]
Looking at the current implementation, I can't see how you solve the issue of re-processing the events after restarting your application.

I am asking because we are making deploys usually weekly, but sometimes multiple releases per day. 

You initialize the `lastProcessedId` in the Poller. 
````
public abstract class AbstractProjectionPoller {

    @PostConstruct
    void instantiate() {
        this.mapper = new ObjectMapper();
        this.lastProcessedId = -1L;
    }
````
so it will re-process all events in Scoring Projection: 

````
@Service
public class ScoringProjection {
    @EventListener
    public void onLeadClickedOnPromotionalLinkReCalculateScore(final LeadClickedOnPromotionalLink event) {
        final LeadScore existingScore = leadScoreRepo.findOneByLeadId(event.getIdOfLead());
        final int newScore = recalculateScoreOfLead(event, existingScore.getScore());
        existingScore.setScore(newScore);

        leadScoreRepo.save(existingScore);
    }
````

Am I missing something?

**Comment by eugenp** [comment]
Hey @ieugen - no, you're not missing anything, but keep in mind that this is supporting code for a workshop, meant to show how to start building a CQRS and Event Sourcing system, so it's just the beginning building blocks of the app, nothing you can go to production with. The reason it's kept simple is educational. 
Hope that clears things up. 
Cheers, 
Eugen.
